/** Secret bindings are provisioned with `wrangler secret put` and intentionally
 * do not appear in wrangler.jsonc. Non-secret bindings remain generated by
 * `wrangler types` in worker-configuration.d.ts. */
interface Env {
  DATABASE_URL?: string;
  TINYFISH_API_KEY?: string;
  PARALLEL_API_KEY?: string;
  APOLLO_API_KEY?: string;
  AGENTMAIL_API_KEY?: string;
  AGENTMAIL_WEBHOOK_SECRET?: string;
  AUTOSEND_API_KEY?: string;
  AUTOSEND_BRIAN_API_KEY?: string;
  AUTOSEND_WEBHOOK_SECRET?: string;
  PDL_API_KEY?: string;
  ZEROBOUNCE_API_KEY?: string;
  SENDGRID_API_KEY?: string;
  SENDGRID_WEBHOOK_PUBLIC_KEY?: string;
  INBOUND_WEBHOOK_TOKEN?: string;
  TWILIO_ACCOUNT_SID?: string;
  TWILIO_AUTH_TOKEN?: string;
  TWILIO_FROM_NUMBER?: string;
  CALENDLY_WEBHOOK_SECRET?: string;
  UNSUBSCRIBE_SECRET?: string;
  CALENDLY_BOOKING_URL?: string;
}
