/** Secret bindings are provisioned with `wrangler secret put` and intentionally
 * do not appear in wrangler.jsonc. Non-secret bindings remain generated by
 * `wrangler types` in worker-configuration.d.ts.
 *
 * These are declared optional because not every secret is set in every
 * environment (see e.g. the BOUNCER_API_KEY / CLEAROUT_API_KEY fallback in
 * lead-pipeline.ts). `wrangler types` additionally folds whatever keys exist
 * in a developer's local, gitignored `.dev.vars` into worker-configuration.d.ts
 * as *required* strings, which would otherwise conflict with the optional
 * declarations here when checked against `Cloudflare.Env` (e.g. the `Agent<Env>`
 * base class requires `Env extends Cloudflare.Env`) — so the same optional
 * shape is declared under the `Cloudflare` namespace too. */
interface AppSecretEnv {
  DATABASE_URL?: string;
  TINYFISH_API_KEY?: string;
  PARALLEL_API_KEY?: string;
  APOLLO_API_KEY?: string;
  AGENTMAIL_API_KEY?: string;
  AGENTMAIL_WEBHOOK_SECRET?: string;
  AUTOSEND_API_KEY?: string;
  AUTOSEND_BRIAN_API_KEY?: string;
  AUTOSEND_WEBHOOK_SECRET?: string;
  PDL_API_KEY?: string;
  BOUNCER_API_KEY?: string;
  CLEAROUT_API_KEY?: string;
  SENDGRID_API_KEY?: string;
  SENDGRID_WEBHOOK_PUBLIC_KEY?: string;
  INBOUND_WEBHOOK_TOKEN?: string;
  TWILIO_ACCOUNT_SID?: string;
  TWILIO_AUTH_TOKEN?: string;
  TWILIO_FROM_NUMBER?: string;
  CALENDLY_WEBHOOK_SECRET?: string;
  UNSUBSCRIBE_SECRET?: string;
  CALENDLY_BOOKING_URL?: string;
}
interface Env extends AppSecretEnv {}
declare namespace Cloudflare {
  interface Env extends AppSecretEnv {}
}
